#!/usr/bin/env python3
import argparse
from pathlib import Path
import json
import csv


def main():
    parser = argparse.ArgumentParser(
        description="Extract trend definitions from Vendor specification file"
    )

    parser.add_argument("-c", "--config", default="config.json", type=Path)
    parser.add_argument("specifications_file", type=Path)
    parser.add_argument("output_file", type=Path)

    args = parser.parse_args()

    with args.config.open() as config_file:
        config = json.load(config_file)

    trend_data_source = config["trend_extraction"]["data_source"]

    granularity = "5m"

    data_type_mapping = {
        "integer": "integer",
        "real": "numeric",
    }

    default_data_type = "numeric"

    trends = []

    with args.specifications_file.open() as meas_def_file:
        csvreader = csv.reader(meas_def_file, delimiter=",")

        # Skip the header
        next(csvreader)

        for row in csvreader:
            name = row[0]
            entity_type = row[3]
            data_type = data_type_mapping.get(row[2], default_data_type)
            description = row[4]
            section = row[5]

            trends.append({
                "data_source": trend_data_source,
                "entity_type": entity_type,
                "granularity": granularity,
                "part": "default",
                "name": name,
                "data_type": data_type,
                "description": description,
                "time_aggregation": "sum",
                "entity_aggregation": "sum",
                "extra_data": {
                    "3GPP": {
                        "section": section,
                    },
                }
            })

    with args.output_file.open("wt") as trends_file:
        json.dump(trends, trends_file, indent=2)


if __name__ == "__main__":
    main()
