[workspace]
members = [
    "crates/minerva",
    "crates/admin-cli",
    "crates/admin-service",
    "crates/integration-tests"
]

[workspace.package]
version = "1.5.3"
authors = ["Alfred Blokland <alfred.blokland@hendrikx-itc.nl>"]
edition = "2021"
license = "GPL-3.0-or-later"
