# Fast buildable Dockerfile for demo purposes
#
# - Does not rely on 1Optic's internal Docker registries
# - Used in `docker-compose.yml`

FROM docker.io/citusdata/citus:14.2.0@sha256:d0d4e67f4715c52e9909e83d61377b5b085a76ba8d82d529178fef10d1bf5f98

# Install 1Optic's Minerva ETL and PostGIS
ENV POSTGIS_MAJOR=3
RUN apt-get update && apt-get install -y --no-install-recommends \
 curl \
 "postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR" \
 && curl -fsS https://pkgs.1optic.io/minerva-cli_9.45.3-1_amd64.deb -o minerva.deb \
 && dpkg -i minerva.deb \
 && rm minerva.deb \
 && rm -rf /var/lib/apt/lists/*

COPY ./container/010_initdb-postgis.sh /docker-entrypoint-initdb.d/

# Load a Minerva instance definition mounted at /minerva-instance
COPY ./container/020_load-minerva-instance.sh /docker-entrypoint-initdb.d/
