# Citus Docker image + Minerva CLI for Minerva instance testing
#
# Place a Minerva instance in directory '/minerva-instance' and it is loaded on container start.

FROM harbor.hendrikx-itc.nl/1optic/rust-ci:1.99.0@sha256:b9b0bb7212d6f443b3a8160157dffa5084374fb9969208dde4d3b2273b07d545 AS build

COPY . /src
WORKDIR /src

RUN cargo build --package minerva-cli --release --target=x86_64-unknown-linux-musl

FROM docker.io/citusdata/citus:14.2.0@sha256:d0d4e67f4715c52e9909e83d61377b5b085a76ba8d82d529178fef10d1bf5f98

COPY --from=build /src/target/x86_64-unknown-linux-musl/release/minerva /usr/bin/

COPY ./container/020_load-minerva-instance.sh /docker-entrypoint-initdb.d/

# Install PostGIS
ENV POSTGIS_MAJOR=3

RUN apt-get update \
      && apt-get install -y --no-install-recommends \
           postgresql-$PG_MAJOR-postgis-$POSTGIS_MAJOR \
      && rm -rf /var/lib/apt/lists/*

COPY ./container/010_initdb-postgis.sh /docker-entrypoint-initdb.d/
